title : TheChels.me
description : Short form blogging and blogging directory
tagline : Short form blogging and blogging directory
safe: true
auto: true
server: true
future: false
lsi: false
paginate: 4
markdown: rdiscount
timezone: Europe/London
source:      .
destination: ./_site
layouts:     ./_layouts
includes:     ./_includes
disqus_shortname: thechelsme
google_analytics_id: True
permalink: /:year/:month/:day/:title

## Variables
baseurl: http://thechels.me
url : http://thechels.me
production_url : http://thechels.me
