title : TheChels.me
description : Chelsea FC Blogging
tagline : Chelsea FC Blogging
safe: true
auto: true
future: false
lsi: false
paginate: 3
markdown: rdiscount
timezone: Europe/London
source:      .
destination: ./_site
layouts:     ./_layouts
includes:     ./_includes
disqus_shortname: thechelsme
permalink: /:categories/:title/

## Variables
baseurl: /
url : http://thechels.me
production_url : http://thechels.me
